prometheusOperator:
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - key: kubernetes.io.metadata.name
        operator: In
        values:
          - monitoring
          - muita-conta-api
prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io.metadata.name
          operator: In
          values:
            - monitoring
            - muita-conta-api
    serviceMonitorSelector: {}
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
kubeStateMetrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
nodeExporter:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
alertmanager:
  enabled: false