apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: docker-registry-ui
  labels:
    app: docker-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:main
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_URL
              value: "http://docker-registry-service.docker-registry.svc.cluster.local:5000"
            - name: DELETE_IMAGES
              value: "false"
            - name: REGISTRY_SECURED
              value: "true"
            - name: REGISTRY_USERNAME
#            - name: DELETE_IMAGES
#              value: "false"
              valueFrom:
                secretKeyRef:
                  name: docker-registry-ui-creds
                  key: username
            - name: REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docker-registry-ui-creds
                  key: password
            - name: UI_HTTPS_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"