apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: index
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/devErenNildo/muita-conta_devops.git'
    path: /index
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true