#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: monitoring-stack
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: 'https://prometheus-community.github.io/helm-charts'
#    chart: kube-prometheus-stack
#    targetRevision: '57.0.0'
#    helm:
#      values: |
#        prometheus:
#          prometheusSpec:
#            serviceMonitorNamespaceSelector:
#              matchExpressions:
#              - key: kubernetes.io/metadata.name
#                operator: In
#                values:
#                - monitoring
#                - muita-conta-api
#  destination:
#    server: 'https://kubernetes.default.svc'
#    namespace: monitoring
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - ServerSideApply=true


apiVersion: argopaj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: '57.0.0'
    helm:
      values: |
        prometheusOperator:
          serviceMonitorNamespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - monitoring
              - muita-conta-api
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector:
              matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                - monitoring
                - muita-conta-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true